const seedPlugins = [
  ['AFK Rewards Premium + Polygonal Regions','Spigot',3,'2.000 ₫','premium','Hoạt động'],['BotSentry','Spigot',2,'0 ₫','free','Hoạt động'],['CMI - 300+ Commands/Insane Kits/Portals/Essentials/Economy/M','Spigot',5,'0 ₫','free','Hoạt động'],['Challenge Plugin (Nachbildung)','Spigot',1,'0 ₫','free','Hoạt động'],['Citizens','Spigot',4,'0 ₫','free','Hoạt động'],['Crazy Vouchers','Paper',2,'0 ₫','free','Hoạt động'],['GadgetsMenu [Premium]','Spigot',8,'12.000 ₫','premium','Hoạt động'],['Guilds [30% Sale]','Spigot',3,'8.000 ₫','premium','Hoạt động'],['Lands','Paper',6,'15.000 ₫','premium','Hoạt động'],['LiteBans','Spigot',7,'0 ₫','free','Hoạt động'],['MythicMobs','Paper',4,'10.000 ₫','premium','Hoạt động'],['PlaceholderAPI','Spigot',3,'0 ₫','free','Hoạt động'],['ShopGUI+','Spigot',2,'5.000 ₫','premium','Hoạt động'],['TAB','BungeeCord',1,'0 ₫','free','Bản nháp'],['Vault','Spigot',2,'0 ₫','free','Hoạt động'],['WorldEdit','Paper',4,'0 ₫','free','Hoạt động'],['WorldGuard','Paper',4,'0 ₫','free','Hoạt động'],['AdvancedTeleport','Spigot',2,'3.000 ₫','premium','Hoạt động'],['ClearLagg','Spigot',2,'0 ₫','free','Hoạt động'],['DiscordSRV','Spigot',3,'0 ₫','free','Hoạt động'],['Jobs Reborn','Paper',4,'6.000 ₫','premium','Hoạt động'],['LuckPerms','Spigot',3,'0 ₫','free','Hoạt động'],['ProtocolLib','Spigot',3,'0 ₫','free','Hoạt động'],['SuperiorSkyblock2','Spigot',2,'9.000 ₫','premium','Hoạt động']
].map(([name,platform,versions,price,tag,status])=>({name,platform,versions,price,tag,status}));
let plugins=[...seedPlugins], currentPage=1, pageSize=8;
const $=id=>document.getElementById(id);
const initials=name=>name.split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase();
function filtered(){const q=$('searchInput').value.trim().toLowerCase(), platform=$('platformFilter').value, tag=$('tagFilter').value;return plugins.filter(p=>(!q||p.name.toLowerCase().includes(q))&&(platform==='all'||p.platform.toLowerCase()===platform)&&(tag==='all'||p.tag===tag))}
function render(){const list=filtered(), totalPages=Math.max(1,Math.ceil(list.length/pageSize));if(currentPage>totalPages)currentPage=totalPages;const start=(currentPage-1)*pageSize, shown=list.slice(start,start+pageSize);$('pluginRows').innerHTML=shown.map(p=>`<tr><td><div class="plugin-title"><span class="plugin-logo">${initials(p.name)}</span><span>${p.name}</span>${p.tag==='premium'?'<span class="tag premium">Premium</span>':'<span class="tag">Miễn phí</span>'}</div></td><td>${p.platform}</td><td><span class="version-count">${p.versions}</span></td><td><span class="price">${p.price}</span></td><td><span class="state ${p.status==='Bản nháp'?'draft':''}"><span>●</span>&nbsp;${p.status}</span></td><td><div class="row-actions"><button class="row-button version-btn" data-name="${p.name}">＋ Phiên bản</button><button class="row-button" data-name="${p.name}">Chi tiết</button></div></td></tr>`).join('');$('emptyState').hidden=shown.length>0;$('resultLabel').textContent=`${list.length} plugin`;$('paginationLabel').textContent=list.length?`Hiển thị ${start+1}–${Math.min(start+pageSize,list.length)} trong ${list.length} plugin`:'Không có kết quả';$('totalPlugins').textContent=plugins.length;$('navPluginCount').textContent=plugins.length;$('totalVersions').textContent=plugins.reduce((a,p)=>a+p.versions,0);$('pageButtons').innerHTML=Array.from({length:totalPages},(_,i)=>`<button class="page-button ${i+1===currentPage?'current':''}" data-page="${i+1}">${i+1}</button>`).join('');document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{currentPage=+b.dataset.page;render()});document.querySelectorAll('.version-btn').forEach(b=>b.onclick=()=>openModal('version',b.dataset.name));}
function openModal(mode='plugin',name=''){ $('modalBackdrop').hidden=false;$('pluginForm').reset();$('modalTitle').textContent=mode==='version'?`Thêm phiên bản mới`:'Thêm plugin mới';$('modalDescription').textContent=mode==='version'?`Đang thêm phiên bản cho “${name}”.`:'Tạo plugin mới để bắt đầu quản lý các phiên bản.';$('pluginForm').dataset.mode=mode;$('pluginForm').dataset.name=name;if(mode==='version'){$('pluginName').value=name;$('pluginName').disabled=true;$('pluginVersion').value='1.0.0';}else $('pluginName').disabled=false;$('pluginName').focus()}
function closeModal(){$('modalBackdrop').hidden=true;$('pluginName').disabled=false}
document.querySelectorAll('#searchInput,#platformFilter,#tagFilter').forEach(el=>el.addEventListener('input',()=>{currentPage=1;render()}));$('pageSize').onchange=e=>{pageSize=+e.target.value;currentPage=1;render()};$('addPluginBtn').onclick=()=>openModal();$('closeModal').onclick=closeModal;$('cancelModal').onclick=closeModal;$('modalBackdrop').onclick=e=>{if(e.target===e.currentTarget)closeModal()};$('refreshBtn').onclick=()=>{render();showToast('Danh sách đã được làm mới')};document.addEventListener('keydown',e=>{if(e.key==='/'&&document.activeElement.tagName!=='INPUT'){e.preventDefault();$('searchInput').focus()}if(e.key==='Escape')closeModal()});$('pluginForm').onsubmit=e=>{e.preventDefault();const f=e.currentTarget;if(f.dataset.mode==='version'){const p=plugins.find(x=>x.name===f.dataset.name);if(p)p.versions++;showToast('Đã thêm phiên bản mới')}else{plugins.unshift({name:$('pluginName').value.trim(),platform:$('pluginPlatform').value,versions:1,price:Number($('pluginPrice').value||0).toLocaleString('vi-VN')+' ₫',tag:$('pluginTag').value,status:'Hoạt động'});showToast('Đã tạo plugin mới')}closeModal();currentPage=1;render()};let toastTimer;function showToast(message){$('toast').textContent='✓  '+message;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),2500)}render();
function deletePlugin(name){if(!window.confirm(`Bạn có chắc muốn xóa plugin “${name}” không?`))return;plugins=plugins.filter(p=>p.name!==name);showToast(`Đã xóa plugin “${name}”`);render()}
document.addEventListener('click',e=>{const button=e.target.closest('.delete-btn');if(button)deletePlugin(button.dataset.name)});
const tableObserver=new MutationObserver(()=>document.querySelectorAll('.row-actions').forEach(actions=>{if(actions.querySelector('.delete-btn'))return;const detail=actions.querySelector('.row-button:not(.version-btn)');if(!detail)return;const button=document.createElement('button');button.className='row-button delete-btn';button.dataset.name=detail.dataset.name;button.textContent='Xóa';actions.appendChild(button)}));
tableObserver.observe($('pluginRows'),{childList:true,subtree:true});
render();
let authMode='login';
const authUsers=()=>JSON.parse(localStorage.getItem('pluginVaultUsers')||'[]');
const setAuthMode=mode=>{authMode=mode;document.querySelectorAll('.auth-tab').forEach(tab=>tab.classList.toggle('active',tab.dataset.authMode===mode));$('authTitle').textContent=mode==='login'?'Đăng nhập':'Tạo tài khoản';$('authSubtitle').textContent=mode==='login'?'Đăng nhập để quản lý kho plugin của bạn.':'Tạo tài khoản admin để bắt đầu quản lý kho.';$('authSubmit').textContent=mode==='login'?'Đăng nhập':'Tạo tài khoản';$('nameField').hidden=mode==='login';$('confirmField').hidden=mode==='login';$('authName').required=mode==='register';$('authConfirm').required=mode==='register';$('authError').textContent=''};
const showApp=()=>{const user=JSON.parse(localStorage.getItem('pluginVaultSession')||'null');if(!user){$('authScreen').hidden=false;$('appShell').hidden=true;return}$('authScreen').hidden=true;$('appShell').hidden=false;$('userAvatar').textContent=(user.name||user.email).split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase();};
document.querySelectorAll('.auth-tab').forEach(tab=>tab.onclick=()=>setAuthMode(tab.dataset.authMode));
$('authForm').onsubmit=e=>{e.preventDefault();const email=$('authEmail').value.trim().toLowerCase(),password=$('authPassword').value,users=authUsers();if(authMode==='register'){if(password!==$('authConfirm').value)return $('authError').textContent='Mật khẩu xác nhận không khớp.';if(users.some(user=>user.email===email))return $('authError').textContent='Email này đã được đăng ký.';const user={name:$('authName').value.trim(),email,password,role:'admin'};localStorage.setItem('pluginVaultUsers',JSON.stringify([...users,user]));localStorage.setItem('pluginVaultSession',JSON.stringify(user));showApp();showToast('Tạo tài khoản thành công')}else{const user=users.find(item=>item.email===email&&item.password===password);if(!user)return $('authError').textContent='Email hoặc mật khẩu không đúng.';localStorage.setItem('pluginVaultSession',JSON.stringify(user));showApp();showToast('Đăng nhập thành công')}};
$('logoutBtn').onclick=()=>{localStorage.removeItem('pluginVaultSession');setAuthMode('login');$('authForm').reset();showApp()};
showApp();
